### ISSUE TITLE
Add a Note from a date/time given

### ISSUE THREAD

**Issue by CooperBarrett** [khuttun/NotificationNotes#12]
*I am French and I use google translation*

Hello,

Congratulations on this open source, simple and effective application.

I do not know if it is possible but it would be possible to add the following functionality:

- **Add a Note from a date / time given ?**

It may take from a few simple but I think it would really be a "plus" to the application.

Thank you and good luck

**Comment by khuttun** [comment]
Do you mean that the notification would automatically appear at given time?

**Comment by CooperBarrett** [comment]
Yes, absolutely, that we can set the date on which notification will be displayed.

**Comment by khuttun** [comment]
This kind of behavior can already be achieved with the basic Android Calendar reminders. As I'd like to keep Notification Notes simple and not duplicate functionality already present in other apps, I don't think I'll implement this feature now. You can of course fork this repo and implement it yourself, if you want.
