### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Natureshadow** [khuttun/NotificationNotes#14]
The app should start automatically so notes survive reboots.

**Comment by khuttun** [comment]
Good idea. Let's see how this could be implemented.

**Comment by khuttun** [comment]
It looks like the notification handling would have to be refactored to a separate service, listen for BOOT_COMPLETED action, and start the service when the action is received.

**Comment by Natureshadow** [comment]
Thanks for implementing this so quickly ☺!

Now it's the most simplistic, straight-forward and helpful notes app I found.
