### ISSUE TITLE
Add ability to edit existing notes

### ISSUE THREAD

**Issue by khuttun** [khuttun/NotificationNotes#15]

**Comment by alanthehat** [comment]
If that proves intractable the ability to cut&paste would provide a workaround & would be independently useful

**Comment by leoauri** [comment]
Yes, please!!

**Comment by xt1072** [comment]
+1 ...Any timetable on this? Being unable to edit existing notes is pretty limiting.

**Comment by khuttun** [comment]
I've been quite busy recently, but this will be the next thing I'll look into.
