### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by Poussinou** [khuttun/NotificationNotes#27]
Hi @khuttun 

I found [this app](https://play.google.com/store/apps/details?id=com.vozisov.notifynotes) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide a link to this repo and some screenshots of your own app.

**Comment by khuttun** [comment]
Hi. Thanks for reporting this. So the license and copyright information can't be found anywhere from the app UI?

**Comment by Poussinou** [comment]
No they can't be found in the app UI nor the Play Store description...
